jenkins:
  systemMessage: "Scheme Jenkins Readme: https://github.com/schemeorg-community/server-configuration/tree/master/jenkins"
  numExecutors: 0
  nodes:
      - permanent:
        mode: NORMAL
        name: "agent1"
        labelString: "docker"
        numExecutors: 8
        remoteFS: "/home/jenkins/agent"
        launcher:
          SSHLauncher:
            host: "jenkins-agent"
            port: 22
            credentialsId: agent_ssh
            launchTimeoutSeconds: 60
            maxNumRetries: 3
            retryWaitTime: 30
            sshHostKeyVerificationStrategy:
              manuallyTrustedKeyVerificationStrategy:
                requireInitialManualTrust: false
  authorizationStrategy:
    projectMatrix:
      entries:
      - group:
          name: "authenticated"
          permissions:
          - "Job/Read"
          - "Overall/Read"
      # Can be used to login if oauth fails
      #- user:
          #name: "admin"
          #permissions:
          #- "Overall/Administer"
      - user:
          name: "lassik"
          permissions:
          - "Overall/Administer"
      - user:
          name: "anonymous"
          permissions:
          - "Job/Read"
          - "Overall/Read"
  securityRealm:
    # Can be used to login if oauth fails
    # comment out the oauth and uncomment this and user part above
    #local:
      #allowsSignup: false
      #users:
        #- id: admin
          #name: admin
          #password: "${readFile:/secrets/adminpassword}"
    github:
      clientID: "${readfile:/secrets/github_oauth_clientid}"
      clientSecret: "${readfile:/secrets/github_oauth_secret}"
      githubApiUri: "https://api.github.com"
      githubWebUri: "https://github.com"
      oauthScopes: "read:org,user:email,repo"

appearance:
  pipelineGraphView:
    showGraphOnBuildPage: true
    showGraphOnJobPage: true

credentials:
  system:
    domainCredentials:
       - credentials:
           - basicSSHUserPrivateKey:
               scope: GLOBAL
               id: agent_ssh
               username: "jenkins"
               description: "SSH key for jenkins agent"
               privateKeySource:
                 directEntry:
                   privateKey: "${readFile:/secrets/id_rsa}"

jobs:
  - script: >
      folder('arvyy') {
        displayName: 'arvyy'
        properties {
          authorizationMatrix {
            entries {
              user {
                name('arvyy')
                permissions([ 'Credentials/Create', 'Credentials/Delete', 'Credentials/Update', 'Credentials/View', 'Job/Build', 'Job/Cancel' ])
              }
            }
          }
        }
      }
  - script: >
      folder('arvyy/index_scheme_org') {
        displayName: 'index.scheme.org'
      }
  - script: >
      multibranchPipelineJob('arvyy/index_scheme_org/build') {
        displayName: 'Build and deploy'
        branchSources {
          git {
              id('github')
              remote('https://github.com/schemeorg-community/scheme-index-site')
          }
        }
        orphanedItemStrategy {
          discardOldItems {
              numToKeep(10)
          }
        }
      }
  - script: >
      folder('arvyy/r7rs_large_work') {
        displayName: 'r7rs-large reference implementation'
      }
  - script: >
      multibranchPipelineJob('arvyy/r7rs_large_work/test') {
        displayName: 'Test'
        branchSources {
          git {
              id('github')
              remote('https://github.com/arvyy/r7rs-work')
          }
        }
        triggers {
          cron('0 * * * *')
        }
      }
  - script: >
      folder('lassik') {
        displayName: 'lassik'
        properties {
          authorizationMatrix {
            entries {
              user {
                name('lassik')
                permissions([ 'Credentials/Create', 'Credentials/Delete', 'Credentials/Update', 'Credentials/View', 'Job/Build', 'Job/Cancel' ])
              }
            }
          }
        }
      }
