services:
  jenkins-controller:
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    environment:
      - CASC_JENKINS_CONFIG=/config/jenkins.yml
    volumes:
      - ./config:/config
      - ./id_rsa:/secrets/id_rsa
      - ./schemeists_email_username:/secrets/schemeists_email_username
      - ./schemeists_email_password:/secrets/schemeists_email_password
      - ./adminpassword:/secrets/adminpassword
      - ./github_oauth_clientid:/secrets/github_oauth_clientid
      - ./github_oauth_secret:/secrets/github_oauth_secret
      - /home/jenkins/jenkins-data:/var/jenkins_home
    ports:
      - 8080:8080
