services:
  jenkins-controller:
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    environment:
      - CASC_JENKINS_CONFIG=/config/jenkins.yml
    volumes:
      - ./config:/config
      - ./id_rsa:/secrets/id_rsa
      - ./adminpassword:/secrets/adminpassword
      - ./github_oauth_clientid:/secrets/github_oauth_clientid
      - ./github_oauth_secret:/secrets/github_oauth_secret
      - /home/jenkins/jenkins-data:/var/jenkins_home
    ports:
      - 8080:8080
  jenkins-agent:
    env_file: ./agent.env
    build:
      context: .
      dockerfile: Dockerfile.agent
      args:
        DOCKER_GROUP: '${DOCKER_GROUP}'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
