FROM jenkins/jenkins:latest-jdk21
RUN jenkins-plugin-cli --plugins 'github-branch-source:latest configuration-as-code:latest ssh-slaves:latest credentials-binding:latest subversion:latest job-dsl:latest pipeline-model-definition:latest pipeline-build-step:latest ansible:latest git:latest workflow-aggregator:latest docker-workflow:latest ws-cleanup:latest ssh-agent:latest matrix-auth:latest'
